{% set name = "mysqlx-connector-python" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mysql/mysql-connector-python/archive/{{ version }}.tar.gz
  sha256: 72c75ccb759cee31474906538b3132f3e26bc91d2913b415ea10d699876dbf9c
  patches:
    - patches/0001-Be-compatible-with-current-libprotobuf-pin.patch
    - patches/0002-Revert-Fix-MacOS-wheels-platform-tag.patch
    - patches/0003-Use-C-17.patch
    - patches/0004-Link-to-abseil_dll-on-Windows.patch
    - patches/0005-Don-t-ignore-user-provided-xtra-compile-link-args.patch

build:
  number: 4

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config
    - libprotobuf
  host:
    - python
    - pip
    - setuptools
    - libprotobuf
    - libabseil
    - protobuf
  run:
    - python
    - protobuf

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - mysqlx
    - mysqlx.protobuf


about:
  home: https://dev.mysql.com/doc/connector-python/en/
  license: GPL-2.0-or-later WITH Universal-FOSS-exception-1.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Python driver for communicating with MySQL servers
  dev_url: https://github.com/mysql/mysql-connector-python/
  description: |
    MySQL Connector/Python is a standardized database driver for Python
    platforms and development.
  doc_url: http://dev.mysql.com/doc/connector-python/en/index.html
  dev_url: https://github.com/mysql/mysql-connector-python

extra:
  recipe-maintainers:
    - nehaljwani
